### ISSUE TITLE
Maybe depend on kubeclient 1.1.2

### ISSUE THREAD

**Issue by modax** [garethr/garethr-kubernetes#10]
Hi,

this is not a real issue so you may close it but you may revert https://github.com/garethr/garethr-kubernetes/commit/69b379c883a6968b9be336307af127d8a0306da9 and depend on Kubeclient 1.1.2 instead which already has https://github.com/abonas/kubeclient/pull/152

**Comment by garethr** [comment]
Yup :) I put up a PR for it to then find it in the version released an hour before. I should have checked with master. https://github.com/abonas/kubeclient/pull/160

I've left it in for backwards compatibility for the moment, but will pull out in a future release.
