### ISSUE TITLE
Daemon Sets

### ISSUE THREAD

**Issue by nickschuch** [garethr/garethr-kubernetes#15]
Hi!

Looking to send a PR to add this type.

Just wondering how I get started.

**Comment by garethr** [comment]
Hi @nickschuch. Sorry for the long delay on getting back to you here. The types and providers are auto-generated using https://github.com/garethr/puppet-swagger-generator.

I have a PR up which should support daemon-sets (and other new and beta resources) if this is still of interest. https://github.com/garethr/garethr-kubernetes/pull/18

**Comment by garethr** [comment]
I've merged #18 and this should now be available in master
