### ISSUE TITLE
Invalid parameter apiVersion(:apiVersion)

### ISSUE THREAD

**Issue by olblak** [garethr/garethr-kubernetes#28]
When I execute a kubernetes_daemon_set generated by puppet kubernetes convert fluentd.yaml:
I got
Error: /Stage[main]/Main/Kubernetes_daemon_set[fluentd]: Could not evaluate: Invalid parameter apiVersion(:apiVersion)
Does it ring a bell to someone?

**Comment by garethr** [comment]
This was fixed in 0.4 I think with the referenced commit. Sorry, just cleaning up issues now.
